---
- name: Install required packages
  apt:
    name: libssl-dev
    update_cache: yes
    state: latest

- name: Git Clone source
  git:
    repo: https://github.com/cossacklabs/themis.git
    dest: "{{ home_directory }}/themis"
    force: yes
    accept_hostkey: yes
  register: git_clone_themis_finished

- name: Make install
  make:
    chdir: "{{ home_directory }}/themis"
    target: install
  when: git_clone_themis_finished.changed
