- name: Git Clone Repo
  git:
    repo: "{{ repo }}"
    dest: "{{ home_directory }}/{{ app }}"
    force: yes
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Install NPM packages
  npm:
    path: "{{ home_directory }}/{{ app }}"
    unsafe_perm: yes
    production: yes
  when: git_clone_app_finished.changed
  tags:
    - setup
    - update

- name: Add .env file
  copy:
    src: .env
    dest: "{{ home_directory }}/{{ app }}/.env"
  tags:
    - setup

- name: Stop APP
  command: forever stop "{{ app }}"
  ignore_errors: yes
  tags:
    - restart
    - stop
    - update

- name: Start APP
  command:
    cmd: forever start -a --uid "{{ app }}" app/server.js
    chdir: "{{ home_directory }}/{{ app }}"
  environment:
    NODE_ENV: production
    PORT: "{{ app_port }}"
  tags:
    - restart
    - start
    - update
