all:
  children:
    dev:
      hosts:
        '127.0.0.1':
          ansible_ssh_port: 2222
          ansible_user: vagrant
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
          base_url: http://vagrant.local
